### ISSUE TITLE
Incorrect read-in of *.mol2 files

### ISSUE THREAD

**Issue by iGulitch** [Isra3l/ligpargen#30] opened 2024-09-06 14:38 UTC
Hello!

I've noticed that ligpargen reads in `*.mol2` files incorrectly. Namely, it uses the x coordinate of an atom as its name and writes it out like this in all output files. Such a problem doesn't exist for `*.mol`, `*.pdb` formats and SMILES.

**Comment by Isra3l** [comment] 2024-12-17 10:32
Dear iGulitch,

I cannot reproduce the error with my MOL2 files and everything works as expected on my end. I recommend double-checking the format of your MOL2 inputs. You could use obabel to regenerate the file and see if any errors occur.

If the issue persists, please share the problematic MOL2 file here so I can take a closer look. I will proceed with closing the thread.

Best,

Israel

**Closed by Isra3l** 2024-12-17 10:32 UTC
