### ISSUE TITLE
Support of other input file formats except for _MOL_, _PDB_?

### ISSUE THREAD

**Issue by iGulitch** [Isra3l/ligpargen#28] opened 2024-08-22 12:49 UTC
Hello, [it's written](https://github.com/Isra3l/ligpargen?tab=readme-ov-file#usage) that **Ligpargen** works with `any input format supported by Open Babel`. However, it struggles to work with _SDF_ files, e.g. the commands :
```
APP="ligpargen"
MOL="6PPD"
ligpargen -i '${MOL}.sdf' -n ${MOL} -p ${MOL} -r MOL -c 0 -o 0 -cgen CM1A"
```
give :
```
Explicit valence for atom # 0 N, 7, is greater than permitted
Traceback (most recent call last):
  File "/opt/conda/envs/ligpargen/bin/ligpargen", line 33, in <module>
    sys.exit(load_entry_point('LigPargen', 'console_scripts', 'ligpargen')())
  File "/ligpargen/ligpargen/ligpargen.py", line 504, in main
    molname=args.molname, workdir= args.path, debug= args.debug)
  File "<string>", line 17, in __init__
  File "/ligpargen/ligpargen/ligpargen.py", line 174, in __post_init__
    moleculeRDkit, newIndexToOriginalIndex, atomsNameOriginal, residueNameOriginal = utilities.generateRDkitMolecule(self.ifile, self.smile, self.workdir, molnameA, self.debug)
  File "/ligpargen/ligpargen/tools/utilities.py", line 187, in generateRDkitMolecule
    Chem.MolToPDBFile(molecule, sfile)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolfiles.MolToPDBFile(NoneType, str)
did not match C++ signature:
    MolToPDBFile(RDKit::ROMol mol, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filename, int confId=-1, unsigned int flavor=0)
```
The _SDF_ was taken from [here](https://pubchem.ncbi.nlm.nih.gov/compound/13101). Also, the ouput of `pybel.informats` contains `'sdf'`, therefore _SDF_ is in the list of Open Babel supported formats.

On the other hand, reconstruction of the same molecule from the canonical SMILES taken from [the same source](https://pubchem.ncbi.nlm.nih.gov/compound/13101#section=Canonical-SMILES) is successful. Namely, the outcome of the following commands :
```
APP="ligpargen"
MOL="6PPD"
SMILES="CC(C)CC(C)NC1=CC=C(C=C1)NC2=CC=CC=C2"
ligpargen -s '${SMILES}' -n ${MOL} -p ${MOL} -r MOL -c 0 -o 0 -cgen CM1A"
```
is simply `LigParGen finished succesfully!`.

Therefore, the question : except for _PDB_, _MOL_, and _SMILES_, is there any other format supported as an input for **Ligpargen**?

**Comment by Isra3l** [comment] 2024-12-17 10:39
Dear iGulitch,

This is similar to the previous MOL2 issue. I cannot reproduce the error with my SDF files, so I will proceed with closing the thread.

Best,

Israel

**Closed by Isra3l** 2024-12-17 10:39 UTC
